(when (require 'php-mode nil t)
  (add-to-list 'auto-mode-alist '("\\.ctp$" . php-mode))
  (add-hook 'php-mode-hook
            '(lambda ()
               (c-set-offset 'case-label' 2)
               (setq tab-width 2)
               (setq require-final-newline t)
               (setq c-basic-offset 4)
               ;; (setq indent-tabs-mode t)
               (setq show-trailing-whitespace t)
               (c-set-offset 'arglist-intro '+)
               (c-set-offset 'arglist-close 0)
               (hs-minor-mode t)
               ;; (php-manual-url "http://www.php.net/manual/ja")
               ))
  )
