(key-combo-mode 1)
(add-hook 'php-mode-hook 'key-combo-mode)
(add-hook 'ruby-mode-hook 'key-combo-mode)
(key-combo-define-global (kbd "=") '(" = " " == " " === " ))
(key-combo-define-global (kbd "=>") " => ")
(key-combo-define-global (kbd ">=") " >= ")
(key-combo-define-global (kbd "<") "<")
(key-combo-define-global (kbd "<=") " <= ")
(key-combo-define-global (kbd "{") " {")
(key-combo-define-global (kbd "!=") " != ")
(key-combo-define-global (kbd "@") '("@" "$"))
(key-combo-define-global (kbd ".=") " .= ")
(key-combo-define-global (kbd "+=") " += ")
(key-combo-define-global (kbd "-=") " -= ")
(key-combo-define-global (kbd "=~") " =~ ")
